// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: api/event/v1/event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Data          *EventData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_api_event_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEventRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateEventRequest) GetData() *EventData {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentData   *PaymentData           `protobuf:"bytes,1,opt,name=payment_data,json=paymentData,proto3" json:"payment_data,omitempty"`
	PaymentDevice *PaymentDevice         `protobuf:"bytes,2,opt,name=payment_device,json=paymentDevice,proto3" json:"payment_device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_api_event_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventData) GetPaymentData() *PaymentData {
	if x != nil {
		return x.PaymentData
	}
	return nil
}

func (x *EventData) GetPaymentDevice() *PaymentDevice {
	if x != nil {
		return x.PaymentDevice
	}
	return nil
}

type PaymentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IpAddres      string                 `protobuf:"bytes,2,opt,name=ip_addres,json=ipAddres,proto3" json:"ip_addres,omitempty"`
	Location      *Location              `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserEmail     string                 `protobuf:"bytes,7,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	UserPhone     string                 `protobuf:"bytes,8,opt,name=user_phone,json=userPhone,proto3" json:"user_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentData) Reset() {
	*x = PaymentData{}
	mi := &file_api_event_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentData) ProtoMessage() {}

func (x *PaymentData) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentData.ProtoReflect.Descriptor instead.
func (*PaymentData) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentData) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *PaymentData) GetIpAddres() string {
	if x != nil {
		return x.IpAddres
	}
	return ""
}

func (x *PaymentData) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *PaymentData) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentData) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PaymentData) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *PaymentData) GetUserPhone() string {
	if x != nil {
		return x.UserPhone
	}
	return ""
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           string                 `protobuf:"bytes,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           string                 `protobuf:"bytes,2,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_api_event_v1_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Location) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

type PaymentDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDevice) Reset() {
	*x = PaymentDevice{}
	mi := &file_api_event_v1_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDevice) ProtoMessage() {}

func (x *PaymentDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDevice.ProtoReflect.Descriptor instead.
func (*PaymentDevice) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentDevice) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PaymentDevice) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_api_event_v1_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_v1_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_api_event_v1_event_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEventResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateEventResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CreateEventResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateEventResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_event_v1_event_proto protoreflect.FileDescriptor

const file_api_event_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x18api/event/v1/event.proto\x12\bevent.v1\"Q\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.event.v1.EventDataR\x04data\"\x85\x01\n" +
	"\tEventData\x128\n" +
	"\fpayment_data\x18\x01 \x01(\v2\x15.event.v1.PaymentDataR\vpaymentData\x12>\n" +
	"\x0epayment_device\x18\x02 \x01(\v2\x17.event.v1.PaymentDeviceR\rpaymentDevice\"\x89\x02\n" +
	"\vPaymentData\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1b\n" +
	"\tip_addres\x18\x02 \x01(\tR\bipAddres\x12.\n" +
	"\blocation\x18\x03 \x01(\v2\x12.event.v1.LocationR\blocation\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"user_email\x18\a \x01(\tR\tuserEmail\x12\x1d\n" +
	"\n" +
	"user_phone\x18\b \x01(\tR\tuserPhone\".\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\tR\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\tR\x03lon\"9\n" +
	"\rPaymentDevice\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"p\n" +
	"\x13CreateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt2Z\n" +
	"\fEventService\x12J\n" +
	"\vCreateEvent\x12\x1c.event.v1.CreateEventRequest\x1a\x1d.event.v1.CreateEventResponseB<Z:github.com/ikondratev/api-gateway/internal/eventpb;eventpbb\x06proto3"

var (
	file_api_event_v1_event_proto_rawDescOnce sync.Once
	file_api_event_v1_event_proto_rawDescData []byte
)

func file_api_event_v1_event_proto_rawDescGZIP() []byte {
	file_api_event_v1_event_proto_rawDescOnce.Do(func() {
		file_api_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_event_v1_event_proto_rawDesc), len(file_api_event_v1_event_proto_rawDesc)))
	})
	return file_api_event_v1_event_proto_rawDescData
}

var file_api_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_event_v1_event_proto_goTypes = []any{
	(*CreateEventRequest)(nil),  // 0: event.v1.CreateEventRequest
	(*EventData)(nil),           // 1: event.v1.EventData
	(*PaymentData)(nil),         // 2: event.v1.PaymentData
	(*Location)(nil),            // 3: event.v1.Location
	(*PaymentDevice)(nil),       // 4: event.v1.PaymentDevice
	(*CreateEventResponse)(nil), // 5: event.v1.CreateEventResponse
}
var file_api_event_v1_event_proto_depIdxs = []int32{
	1, // 0: event.v1.CreateEventRequest.data:type_name -> event.v1.EventData
	2, // 1: event.v1.EventData.payment_data:type_name -> event.v1.PaymentData
	4, // 2: event.v1.EventData.payment_device:type_name -> event.v1.PaymentDevice
	3, // 3: event.v1.PaymentData.location:type_name -> event.v1.Location
	0, // 4: event.v1.EventService.CreateEvent:input_type -> event.v1.CreateEventRequest
	5, // 5: event.v1.EventService.CreateEvent:output_type -> event.v1.CreateEventResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_event_v1_event_proto_init() }
func file_api_event_v1_event_proto_init() {
	if File_api_event_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_event_v1_event_proto_rawDesc), len(file_api_event_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_event_v1_event_proto_goTypes,
		DependencyIndexes: file_api_event_v1_event_proto_depIdxs,
		MessageInfos:      file_api_event_v1_event_proto_msgTypes,
	}.Build()
	File_api_event_v1_event_proto = out.File
	file_api_event_v1_event_proto_goTypes = nil
	file_api_event_v1_event_proto_depIdxs = nil
}
